import{GIFEncoder,quantize,applyPalette}from'https://cdn.jsdelivr.net/npm/gifenc@1.0.3/+esm';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],canvas=$('#card'),ctx=canvas.getContext('2d',{willReadFrequently:true}),status=$('#status');let portrait=null;
const val=id=>$('#'+id).value,nval=id=>Math.max(1,Math.min(255,+val(id)||1)),pick=a=>a[Math.floor(Math.random()*a.length)],rnd=(a,b)=>Math.floor(Math.random()*(b-a+1))+a;
function rr(c,x,y,w,h,r,f,s='#24241f',lw=3){c.beginPath();c.roundRect(x,y,w,h,r);c.fillStyle=f;c.fill();if(s){c.strokeStyle=s;c.lineWidth=lw;c.stroke()}}
function text(c,t,x,y,z=20,a='left',col='#24241f',wt=800){c.font=`${wt} ${z}px ui-monospace,Menlo,monospace`;c.textAlign=a;c.textBaseline='alphabetic';c.fillStyle=col;c.fillText(String(t),x,y)}
function portraitDraw(c,x,y,w,h,bob=0){if(!portrait){c.fillStyle='#68735e';c.fillRect(x,y,w,h);text(c,'UPLOAD CREATURE',x+w/2,y+h/2,20,'center','#eef4e8');return}c.save();c.beginPath();c.rect(x,y,w,h);c.clip();let sw=portrait.naturalWidth,sh=portrait.naturalHeight,sc=Math.max(w/sw,h/sh),dw=sw*sc,dh=sh*sc;if($('#pixel').checked){let block=+val('pixelSize'),off=document.createElement('canvas');off.width=Math.max(8,Math.round(w/block));off.height=Math.max(8,Math.round(h/block));let o=off.getContext('2d');o.imageSmoothingEnabled=false;o.drawImage(portrait,(off.width-dw/block)/2,(off.height-dh/block)/2,dw/block,dh/block);c.imageSmoothingEnabled=false;c.drawImage(off,x,y,w,h);c.imageSmoothingEnabled=true}else c.drawImage(portrait,x+(w-dw)/2,y+(h-dh)/2+bob,dw,dh);c.restore()}
function stat(c,l,v,x,y,w){text(c,l,x,y,12);text(c,v,x+w,y,12,'right');rr(c,x,y+8,w,10,2,'#ddd4bd','#24241f',2);c.fillStyle=val('accent');c.fillRect(x+2,y+10,(w-4)*Math.min(1,v/150),6)}
function infoPanel(c,page){c.fillStyle='#f6f0dd';c.fillRect(0,500,500,200);if(page===0){text(c,'BASE DATA',28,530,15);stat(c,'HP',nval('hp'),28,557,205);stat(c,'ATK',nval('atk'),267,557,205);stat(c,'DEF',nval('def'),28,607,205);stat(c,'SPD',nval('spd'),267,607,205);text(c,'● STATS',250,676,11,'center','#766f60')}else{const moves=$$('.move').map(e=>e.value.toUpperCase()).filter(Boolean),start=(page-1)*2;text(c,`SPECIAL MOVES ${page}/2`,28,530,15);moves.slice(start,start+2).forEach((m,i)=>{rr(c,28,550+i*55,444,42,5,'#fffaf0','#24241f',2);text(c,`${start+i+1}. ${m}`,43,577+i*55,15)});text(c,`● MOVES ${page}/2`,250,676,11,'center','#766f60')}}
function draw(c,w,h,o={}){c.save();c.scale(w/500,h/700);const page=o.page??0,scan=o.scan??1,bob=o.bob??0,a=val('accent');c.fillStyle='#f6f0dd';c.fillRect(0,0,500,700);c.fillStyle=a;c.fillRect(0,0,500,94);text(c,`NO.${val('number').padStart(3,'0')}`,28,38,15,'left','#fff');text(c,(val('name')||'UNKNOWN').toUpperCase(),28,72,33,'left','#fff');rr(c,374,28,98,38,8,'#fff6df');text(c,val('type').toUpperCase(),423,53,12,'center');rr(c,25,119,450,282,8,'#292a26');c.fillStyle=val('screen');c.fillRect(36,130,428,260);portraitDraw(c,36,130,428,260,bob);if(scan<1){c.fillStyle=`rgba(246,240,221,${1-scan})`;c.fillRect(36,130,428,260);c.fillStyle='#fff';c.fillRect(36,130+260*scan,428,4)}rr(c,25,416,450,73,6,'#fffaf0');text(c,val('species').toUpperCase(),40,445,18);text(c,`HT ${val('height')}`,40,474,13);text(c,`WT ${val('weight')}`,250,474,13);infoPanel(c,page);c.restore()}
function render(page=0){draw(ctx,500,700,{page});$('#pixelOut').textContent=val('pixelSize');document.documentElement.style.setProperty('--accent',val('accent'))}
function randomize(){const names=['EMBER','NOVA','MOSSY','ZAPPA','BUBBLE','FROST','COMET','PIXEL','NIMBUS','ONYX'],types=['FIRE','WATER','GRASS','ELECTRIC','ICE','GHOST','ROCK','PSYCHIC'],classes=['BYTE BEAST','FOREST IMP','SPARK MOUSE','MOON WISP','CAVE CUB','STORM BIRD','DREAM FOX','RUNE FROG'],moves=['PIXEL BURST','NOVA PULSE','QUICK DASH','STATIC FIELD','MOON BEAM','EMBER KICK','FROST BITE','AQUA RUSH','LEAF CUTTER','SHADOW STEP','ROCK CRASH','MIND WAVE'];$('#number').value=String(rnd(1,999)).padStart(3,'0');$('#name').value=pick(names);$('#type').value=pick(types);$('#species').value=pick(classes);$('#height').value=(rnd(3,24)/10).toFixed(1)+' m';$('#weight').value=(rnd(20,900)/10).toFixed(1)+' kg';['hp','atk','def','spd'].forEach(id=>$('#'+id).value=rnd(35,145));$$('.move').forEach((e,i)=>e.value=pick(moves.filter(x=>!$$('.move').slice(0,i).some(q=>q.value===x))));$('#accent').value=pick(['#e84a3c','#3578b8','#4d8b57','#8c58a8','#d58a32','#367f78']);$('#screen').value=pick(['#b9caaa','#b8c9d6','#d2c4a6','#c5b9d4']);render();status.textContent='Random creature data generated. You can edit every field.'}
function download(blob,name){let a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
$('#file').onchange=e=>{let f=e.target.files?.[0];if(!f)return;let im=new Image();im.onload=()=>{portrait=im;render();status.textContent=`Loaded ${f.name}. Image stays local.`};im.src=URL.createObjectURL(f)};
$$('input,select').forEach(e=>e.addEventListener(e.type==='range'?'input':'change',()=>render()));$$('input').forEach(e=>e.addEventListener('input',()=>render()));$('#random').onclick=randomize;$('#rerender').onclick=()=>render();$('#png').onclick=()=>canvas.toBlob(b=>download(b,`${val('name').toLowerCase()}-dex.png`));
$('#gif').onclick=async()=>{let b=$('#gif');b.disabled=true;b.textContent='ENCODING…';status.textContent='Building rotating dex animation…';try{let w=+val('gifSize'),h=Math.round(w*1.4),delay=+val('delay'),fc=document.createElement('canvas');fc.width=w;fc.height=h;let c=fc.getContext('2d',{willReadFrequently:true}),gif=GIFEncoder(),frames=[];for(let i=0;i<7;i++)frames.push({scan:(i+1)/7,page:0,bob:0});for(let p=0;p<3;p++)for(let i=0;i<8;i++)frames.push({scan:1,page:p,bob:Math.sin(i/8*Math.PI*2)*5});for(let i=0;i<frames.length;i++){c.clearRect(0,0,w,h);draw(c,w,h,frames[i]);let rgba=c.getImageData(0,0,w,h).data,pal=quantize(rgba,128),idx=applyPalette(rgba,pal);gif.writeFrame(idx,w,h,{palette:pal,delay:i<7?delay:delay*2,repeat:i===0?0:undefined});await new Promise(r=>setTimeout(r,0))}gif.finish();download(new Blob([gif.bytes()],{type:'image/gif'}),`${val('name').toLowerCase()}-dex.gif`);status.textContent='GIF exported: stats → moves 1–2 → moves 3–4.'}catch(e){console.error(e);status.textContent='GIF export failed. Try a smaller size.'}finally{b.disabled=false;b.textContent='GENERATE GIF'}};
render();